ALTER TABLE users
  ADD COLUMN IF NOT EXISTS onboarding_eligible BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE users
  ALTER COLUMN onboarding_eligible SET DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS onboarding_state (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'SKIPPED')),
  step INTEGER NOT NULL CHECK (step BETWEEN 1 AND 4),
  version INTEGER NOT NULL DEFAULT 1,
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
